"""Add user_email for OAuthToken table

Revision ID: 2e8b87e03fe9
Revises: a1b1c84aed19
Create Date: 2024-02-19 14:34:52.596547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8b87e03fe9'
down_revision: Union[str, None] = 'a1b1c84aed19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
